Use `poetry` to build venv in debian packages
Co-authored-by: Dan Callahan <danc@element.io>
Co-authored-by: Shay <hillerys@element.io>

diff --git a/debian/build_virtualenv b/debian/build_virtualenv
--- a/debian/build_virtualenv
+++ b/debian/build_virtualenv
@@ -30,8 +30,22 @@ case $(dpkg-architecture -q DEB_HOST_ARCH) in
         ;;
 esac
 
-# Use --builtin-venv to use the better `venv` module from CPython 3.4+ rather
-# than the 2/3 compatible `virtualenv`.
+# Manually install Poetry and export a pip-compatible `requirements.txt`
+# We need a Poetry pre-release as the export command is buggy in < 1.2
+if [ -e requirements.txt ]; then
+    # Guard against a possible future where requirements.txt lives in the repo.
+    # Otherwise, calling `poetry export` below would silently clobber it.
+    echo "requirements.txt already exists; aborting" 1>&2
+    exit 1
+fi
+TEMP_VENV="$(mktemp -d)"
+python3 -m venv "$TEMP_VENV"
+source "$TEMP_VENV/bin/activate"
+pip install -U pip
+pip install poetry==1.2.0b1
+poetry export --extras "all test" -o requirements.txt
+deactivate
+rm -rf "$TEMP_VENV"
 
 dh_virtualenv \
     --install-suffix "matrix-synapse" \
@@ -43,7 +57,8 @@ dh_virtualenv \
     --preinstall="wheel" \
     --extra-pip-arg="--no-cache-dir" \
     --extra-pip-arg="--compile" \
-    --extras="all,systemd,test"
+    --extras="all,systemd,test" \
+    --requirements="requirements.txt"
 
 PACKAGE_BUILD_DIR="debian/matrix-synapse-py3"
 VIRTUALENV_DIR="${PACKAGE_BUILD_DIR}${DH_VIRTUALENV_INSTALL_ROOT}/matrix-synapse"
